### ISSUE TITLE
及时雨啊，受我一吻，虽然没试过，但是你就如我最后一根救命稻草，神牛我爱你！！

### ISSUE THREAD

**Issue by fish-ball** [alonehover/cordova-plugin-cmb#1]

**Comment by fish-ball** [comment]
但是这个没有文档哦！能不能简单介绍一下肿么用？跪求在线等！

**Comment by alonehover** [comment]
@fish-ball 不好意思，才看见，直接安装不能用么？

**Comment by fish-ball** [comment]
@alonehover 里面有些限制条件产生了一些限制，我自己正在修改使用，现在卡在了这里：

```
            @Override
            public boolean shouldOverrideUrlLoading(WebView view, String url) {
                // 使用当前的WebView加载页面
                CMBKeyboardFunc kbFunc = new CMBKeyboardFunc((Activity) view.getContext());
                if (kbFunc.HandleUrlCall(view, url) == false) {
                    return super.shouldOverrideUrlLoading(view, url);
                } else {
                    return true;
                }
            }

```

这一段能够进去，但是并没有能够拦截 `http://cmbls/cmbKeyboard?id=_rbKeyboard_...` 这个链接

然后点了密码输入框之后就出现了一个*网页无法打开，net::ERR_NAME_NOT_RESOLVED 的错误*

不知道你遇到过没。

**Comment by alonehover** [comment]
@fish-ball 
当时我没有遇到你说的情况，但是猜测就是参数的问题，导致sdk监听不到url然后调起键盘。返回了false以后页面进行了正常跳转到`http://cmbls/cmbKeyboard?id=_rbKeyboard_...`去了

我看到你改了这里

    CMBKeyboardFunc kbFunc = new CMBKeyboardFunc((Activity) view.getContext());

不知道是不是你传进去的参数的问题？因为我当初是参照他们的sdk demo来写的，传入的是当前的activity, 而拦截操作`kbFunc.HandleUrlCall(view, url)`实现了，如果不是`http://cmbls/cmbKeyboard?id=_rbKeyboard_...`这个链接就返回false.  建议你打下log看看吧，看看url是不是这个链接。
